### ISSUE TITLE
Angular 10 Warning

### ISSUE THREAD

**Issue by Christian-Seiler** [broofa/mime#241]
Angular 10 now gives a warning to users who are using this library due to it being a CommonJS package.

```
WARNING in mime.service.ts depends on mime/lite. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**Comment by broofa** [comment]
Working on it (slowly, obviously).

**Comment by broofa** [comment]
Closing.  `mime@4 (published as `mime@beta`) is ESM-only, which should fix this issue.
