### ISSUE TITLE
I changed the extension of .xlsx to .pdf and then it is showing mime type as application/pdf. It is fivind type based on extension not content type

### ISSUE THREAD

**Issue by shah20** [broofa/mime#243]
### If you have an issue with a specific extension or type

Locate the definition for your extension/type in the [db.json file](https://github.com/jshttp/mime-db/blob/master/db.json) in the `mime-db` project.  Does it look right?

- [ ] No. [File a `mime-db` issue](https://github.com/jshttp/mime-db/issues/new).
- [ ] Yes: Go ahead and submit your issue/PR here and I'll look into it.

**Comment by broofa** [comment]
Working as intended.  This library does maps file names/extensions to mime types, does not inspect file contents.
