### ISSUE TITLE
Does not support AVIF

### ISSUE THREAD

**Issue by JonathanTroyer** [broofa/mime#245]
### If you have an issue with a specific extension or type

Locate the definition for your extension/type in the [db.json file](https://github.com/jshttp/mime-db/blob/master/db.json) in the `mime-db` project.  Does it look right?

- [ ] No. [File a `mime-db` issue](https://github.com/jshttp/mime-db/issues/new).
- [x] Yes: Go ahead and submit your issue/PR here and I'll look into it.

mime-db is now on [version 1.45.0](https://github.com/jshttp/mime-db/releases/tag/v1.45.0), while this package is [still on 1.44.0](https://github.com/broofa/mime/blob/6f5eb3e1559edcbd52445582b4444a0e74119059/package.json#L21).

Is there a particular reason this didn't get bumped by dependabot?

**Comment by broofa** [comment]
Published in 2.4.7
