### ISSUE TITLE
wzrd.in cdn module returns 502 error

### ISSUE THREAD

**Issue by halmos** [broofa/mime#248]
I'm not certain, but I believe that the 502 error is thrown by wzrd.in / Cloudflare CDN when the module is missing. 

Did the CDN module move from `https://wzrd.in/standalone/mime%2flite@latest` and `https://wzrd.in/standalone/mime@latest`?

**Comment by broofa** [comment]
This is a wzrd.in issue.  Their origin server is down or unreachable.

From [cloudflare docs](https://support.cloudflare.com/hc/en-us/articles/115003011431-Troubleshooting-Cloudflare-5XX-errors#502504error): "An HTTP 502 or 504 error occurs when Cloudflare is unable to establish contact with your origin web server"

**Comment by broofa** [comment]
Looks like it's back.
