### ISSUE TITLE
getTypes interface error

### ISSUE THREAD

**Issue by fnoquiq** [broofa/mime#255]
The `lookup()` function has been changed to `getType()`. I believe the interface is out of date.

My code:
```ts
import mime from 'mime'; // mime: "^2.5.2"
const ContentType = mime.getType(originalPath);
```

Typescript error:
`Property 'getType' does not exist on type 'typeof import("....../node_modules/@types/mime/index")'.`

Lookup type:
<img width="950" alt="Captura de Tela 2021-02-22 às 18 44 10" src="https://user-images.githubusercontent.com/11557379/108774185-1a06af80-753e-11eb-8bc2-b4f4e58c0bef.png">

**Comment by jotave42** [comment]
I have the same issue here. I've just changed it in the `index.d.ts` but it would be nice to see an update to solve this issue

**Comment by marc-wittwer** [comment]
This installs the right types.
`npm i @types/mime`

However, the v2 types should be installed automatically with `npm i mime`

**Comment by fnoquiq** [comment]
> This installs the right types.
> `npm i @types/mime`
> 
> However, the v2 types should be installed automatically with `npm i mime`

it didn't work

**Comment by Guribeiro** [comment]
I've got the same issue
After installing **@types/mime** it started to working as the expected

// mime: "^2.5.2"

`import { getType } from 'mime';`
`const ContentType = getType(originalPath);`

**Comment by andrewdingcanada8** [comment]
same problem here with mime: "^2.5.2"

**Comment by broofa** [comment]
1. This appears to be an issue with `@types/mime`, not this module (`mime`), right?
2. The `lookup()` method was removed four (4) years ago (in both theses modules).  E.g. in mime/types... https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b59dee51308fa0d8e1979ea4504356790f8c4d14, so I'm not sure how/why this error would be surfacing now.

Closing, as this doesn't appear to be an issue with this project.  'Happy to reopen if someone wants to explain what tangible actions should stem from this in this module.
