### ISSUE TITLE
does it detect mimetype from base64 string

### ISSUE THREAD

**Issue by MeRahulAhire** [broofa/mime#256]
I have a question that does this library supports knowing mimeTypes from buffer or base64 string?

**Comment by broofa** [comment]
No.  It only maps between file extensions (strings) and mime types.  It does not derive mime type from file contents.

**Comment by MeRahulAhire** [comment]
if possible could you add a support for it? or is it just not possible to detect straight away from buffer or base64.  Any suggestions..

**Comment by broofa** [comment]
Out of scope of this project.  (It’s non-trivial to implement)
