### ISSUE TITLE
.msg file upload error

### ISSUE THREAD

**Issue by wookiehunter** [broofa/mime#266]
### If you have an issue with a specific extension or type

Locate the definition for your extension/type in the [db.json file](https://github.com/jshttp/mime-db/blob/master/db.json) in the `mime-db` project.  Does it look right?

- [ ] No. [File a `mime-db` issue](https://github.com/jshttp/mime-db/issues/new).
- [x ] Yes: Go ahead and submit your issue/PR here and I'll look into it.

H, when uploading a .msg file in a react build I am getting a status 500 error that points to the file/row where I specify the allowed extensions (jpeg|jpg|png|pdf|gif|doc|docx|xls|xlsx|msg). Every other file type works fine but msg files do not. Please advise.

**Comment by broofa** [comment]
Need more info.  500 error is a generic "internal server error".  You'll need to identify what specifically is broken in this module and what change you need made for me to act on this.

I'll reopen if/when it's established this is an actionable issue.
