### ISSUE TITLE
Wrong type definition

### ISSUE THREAD

**Issue by kasir-barati** [broofa/mime#268]
### If you have an issue with a specific extension or type

![What I have to use in TS](https://user-images.githubusercontent.com/73785723/158395657-d70e5d14-1261-4028-a234-16fa385410f6.png)
 As you see there is something wrong in type definitions.
![And what in reality works without error](https://user-images.githubusercontent.com/73785723/158395796-ae8be467-7f71-4f44-984b-16f4dd062b3f.png)

Node version: v17.6.0
mime version: 3.0.0
OS: Ubuntu
How I import it: `import mimeType from 'mime'`

![And here is what I saw in runtime](https://user-images.githubusercontent.com/73785723/158404193-88ef130b-360d-42b3-a844-7c395dc29012.png)

**Comment by broofa** [comment]
The `extension()` method was removed in mime@2.  Use `getExtension()`.
