### ISSUE TITLE
Typescript bug in Next.js

### ISSUE THREAD

**Issue by ordinary9843** [broofa/mime#285]
Report a TypeScript anomaly, when installing the latest version of mime (3.0.0), in the nestjs environment, ts exports .extension() type functions, which should actually correspond to .getExtension(). Self-installing @type/mime does not improve the situation.

Updated from 2023/09/01:
Using it in this way is wrong: `import mime from 'mime';`
Actually, it should be used like this: `import * as mime from 'mime';`

**Comment by broofa** [comment]
`mime@4` is in beta, and includes built-in TS types.  See README for install instructions (tl;dr: `npm install mime@beta`) Can you give it a try to see if it fixes the the problem

**Comment by broofa** [comment]
'Gonna close this out just to clear up the issue and PR backlog.  If there's still an issue feel free to comment here or open a new issue.  Thanks!

**Comment by kasir-barati** [comment]
@broofa I have the same problem. The is where IDE says it is picking up the types: `module "/home/some/path/node_modules/mime/dist/src/index"`

and `tsc` is not able to compile the project unless I do something ugly like this:

```ts
import * as mime from 'mime';
(mime as any).getType('file.txt');
```

**Comment by kasir-barati** [comment]
And the `mime/lite` does not export `getType`

**Comment by broofa** [comment]
@kasir-barati  'Works for me ...
```
$ npm ls
foo@ /private/tmp/foo
`-- mime@4.0.6

$ node --version
v20.18.1

$ node --experimental-default-type=module -e "import mime from 'mime'; console.log(mime.getType('txt'))"
text/plain

$ node --experimental-default-type=module -e "import * as mime from 'mime'; console.log(mime.default.getType('txt'))"
text/plain
```

Create an MRE and attach it to a new issue if you think this needs further investigation.
