### ISSUE TITLE
application/javascript is deprecated

### ISSUE THREAD

**Issue by JoakimCh** [broofa/mime#286]
> Per the [IANA Media Types registry](https://www.iana.org/assignments/media-types/media-types.xhtml#text), [RFC 9239](https://www.rfc-editor.org/rfc/rfc9239.html), and the [HTML specification](https://html.spec.whatwg.org/multipage/scripting.html#scriptingLanguages:text/javascript), JavaScript content should always be served using the MIME type text/javascript. No other MIME types are considered valid for JavaScript, and using any MIME type other than text/javascript may result in scripts that do not load or run.

Source: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript)

What else does it use that is deprecated? I didn't check.

**Comment by broofa** [comment]
https://github.com/jshttp/mime-db/issues/194
