### ISSUE TITLE
`import {getType} from 'mime'` no longer works in `mime@4`

### ISSUE THREAD

**Issue by broofa** [broofa/mime#295]
As [noted by @MartinX3](https://github.com/broofa/mime/issues/291#issuecomment-1835772138), directly importing properties of the `mime` object - e.g. `import { getType } from 'mime';` - no longer works in mime@4. 

First, it's worth noting that this sort of import was technically never a _documented_ part of the API.  The README has always recommended importing and accessing the API through the `mime` object.  That said, I'm not surprised that some devs prefer this style of import.  And judging by the code, I apparently went out of my way to support it at some point.  So... fine, "we'll allow it." 😄 

That said, I consider the new behavior to be "**working as intended**".  It's a natural consequence of a couple important architectural changes in v4.  Specifically:

1. **Object-based API**.  Having the `mime` API rooted in instances of a `Mime` clas allows for a clean separation between immutable, default objects and mutable, custom objects.  Thus, it makes sense to export the `mime` object as a whole.  This is how the code was structured previously, but the new version really leans into this decision in ways it didn't used to.
2. **Switching to ESM-only**.  ESM doesn't support exporting all properties of an object [by design](https://2ality.com/2014/09/es6-modules-final.html#why-do-we-need-named-exports%3F).  Doing so gets awkward and is arguably a bit of a code-smell.

While maintaining backward compatibility is doable, it would require a couple of code patterns that I don't particularly care for.  And since this is a major-version release I think it's appropriate to drop support at this time.

For those affected by this, my apologies.  There's a couple options...

**Option 1: Patch affected code (recommended)**

For most users, just patch up your existing code.

```js
// Change this:
import {getType} from 'mime';
// ... to this:
import mime from 'mime';

// ... and change calls like this:
const type = getType(someType);
// ... to this:
const type = mime.getType(someType);
```

**Option 2: Create local var(s) bound to the `mime` instance**

If for some reason you have bunch of call sites that you'd rather not deal with updating (why?!?), you can do this.

```js
// Change this:
import {getType} from 'mime';
// ... to this:
import mime from 'mime';
const { getType } = mime.getType.bind(mime);
```

**Option 3: Use dynamic `import()`**

If you happen to be dynamically require()'ing or import()'ing `mime` already, you can just destructure the `defualt` object.  I wouldn't recommend this otherwise, however.

```js
// Change this:
import { getType } from 'mime';
// ... to this:
const { getType } = (await import('mime')).default
```

**Option 4: Create a helper module that binds and exports the desired properties**

Lastly, if you have a bunch of code affected by this and really want to miminize your code churn I suppose you can do something like this.   ('Would love to hear the use case for this, if anyone actually has one.) 

```js
// --- "mime-helper.js" ---
import mime from 'mime';
const getType = mime.getType.bind(mime);
export { getType, getExtension, getAllExtensions };

// Then, elsewhere, change this:
import { getType } from './mime-helper.js';
// ... to this:
import mime from 'mime';
```

**Comment by broofa** [comment]
@MartinX3, 'looks like you've fixed the problem.  Thanks for the report.

**Comment by ericmorand** [comment]
@broofa,

This is wrong and fallacious:

> *Object-based API*. Having the mime API rooted in instances of a Mime class allows for a clean separation between immutable, default objects and mutable, custom objects. Thus, it makes sense to export the mime object as a whole. This is how the code was structured previously, but the new version really leans into this decision in ways it didn't used to.

You created the issue _not_ becasuse the API is Object-based. You created the issue because it is Class-based. Would your API be Object-based but _not_ Class-based, this would work:

```ts
export interface Mime {
  // ...
}

export const createMime = (): Mime => {
  // there is no dependency on `this` hence it allows for the instance to be destructured without any issue
}

export const mime = createMime();
```

I understand that you are allowed to make your own API design decisions, and I'm not making a point about that. My point is that you wrongly affirm that the lack of destructuring support is because of Object-based design, which is not the case.
