### ISSUE TITLE
Version "4.0.1" doesn't include "CommonJS" exports that's crashing projects with "ERR_REQUIRE_ESM" error

### ISSUE THREAD

**Issue by AndreiMrakov** [broofa/mime#303]
**Preconditions:**
Project is configured with `nodemon` and `ts-node`. After updating package to the latest version(`4.0.1`) project starts crashing with error `ERR_REQUIRE_ESM`. After checking sources in npm I've found only esm exports that causes `CommonJS` configured project crash. 

**Solution:**
add different build config for package publisher that will add mapping for `CommonJS` imports that allows to use up-to-date package version.

**Comment by AndreiMrakov** [comment]
I suppose [this article](https://thesametech.com/how-to-build-typescript-project) will help with issue fixing

**Comment by broofa** [comment]
If you need CJS, use `mime@3`.  As a module maintainer I have neither the time nor pain tolerance needed to support both module formats.  Ergo, "ESM only" from v4 forward.

(Just be aware that the MIME mappings for `mime@3` are outdated and I will only be publishing updates for `mime@4+`)

**Comment by AndreiMrakov** [comment]
@broofa What do you think about me creating PR for "ejs" supporting? Will you be kind to merge it or you wanna to separate it on version lvl?

**Comment by broofa** [comment]
@AndreiMrakov "ejs"?  Do you mean ESM?   Not sure what you're proposing.

**Comment by AndreiMrakov** [comment]
@broofa I mean "CommonJS" code where "require" is used instead of "imports"

**Comment by douglasjunior** [comment]
Would be nice to understand the advantages to force the migration to ESM on a package like that.

Because of that, many legacy projects, or even new React Native projects, are unable to update `mime` version.

**Comment by broofa** [comment]
> Would be nice to understand the advantages to force the migration to ESM on a package like that.

Short answer: Supporting CJS and ESM requires time and energy I don't have.

Long answer: [relevant comment thread](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c?permalink_comment_id=3850849#gistcomment-3850849)
