### ISSUE TITLE
TS warnings while compiling with react-scripts

### ISSUE THREAD

**Issue by ondasStevo** [broofa/mime#310]
### Sanity Checks

- [x] This is NOT about a specific MIME type⬌extension mapping.  Such concerns should be addressed in [the `mime-db` project](https://github.com/jshttp/mime-db/issues).  (Be sure to search the issues first.  Odds are good your concern has already been reported.)
- [X] Your issue title is descriptive and specific to the problem (i.e. search-engine friendly)
- [X] You understand what an "MRE" is, and why providing one is important.  (If not, [read this](https://stackoverflow.com/help/minimal-reproducible-example))

### MRE (supporting details)

_Actual behavior:_  I use mime library in my react.js application. Locally for develop I use "react-scripts start" script. It generates these warnings about "No such file or directory" from mime library:
**WARNING in ./node_modules/mime/dist/src/Mime.js**
`Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):`
`Failed to parse source map from 'project_path\node_modules\mime\src\Mime.ts' file: Error: ENOENT: no such file or directory, open 'project_path\node_modules\mime\src\Mime.ts'`

**WARNING in ./node_modules/mime/dist/src/index.js**
`Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):`
`Failed to parse source map from 'project_path\node_modules\mime\src\index.ts' file: Error: ENOENT: no such file or directory, open 'project_path\node_modules\mime\src\index.ts'ts'`

**WARNING in ./node_modules/mime/dist/types/other.js**
`Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):`                                                                                             
`Failed to parse source map from 'project_path\node_modules\mime\types\other.ts' file: Error: ENOENT: no such file or directory, open 'project_path\node_modules\mime\types\other.ts'`

**WARNING in ./node_modules/mime/dist/types/standard.js**
`Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):`
`Failed to parse source map from 'project_path\node_modules\mime\types\standard.ts' file: Error: ENOENT: no such file or directory, open 'project_path\node_modules\mime\types\standard.ts'`

_Expected behavior:_ start project locally without warnings generated by mime library

_Dep versions for investigating:_

- react@18.2.0
- typescript@5.4.5
- react-scripts@5.0.1
- mime@4.0.1

**Comment by broofa** [comment]
Thanks for the report!   I forgot to add the `src` files to the package. (Sheesh!)

Please update to `mime@latest`.  Let me know if you're still seeing this issue and I'll reopen.

**Comment by ondasStevo** [comment]
@broofa Thank you for fast relpy, now it's better :)
Two warnings (_Mime.js_ and _index.js_) are solved. After updated to mime@latest (mime@4.0.2) I got these warnings:

**WARNING in ./node_modules/mime/dist/types/other.js**
`Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):`
`Failed to parse source map from 'project_path\node_modules\mime\types\other.ts' file: Error: ENOENT: no such file or directory, open 'project_path\node_modules\mime\types\other.ts'   `

**WARNING in ./node_modules/mime/dist/types/standard.js**
`Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):`
`Failed to parse source map from 'project_path\node_modules\mime\types\standard.ts' file: Error: ENOENT: no such file or directory, open 'project_path\node_modules\mime\types\standard.ts'`

Thanks.

**Comment by ondasStevo** [comment]
Great! Now it's solved :)
